.TH ENPIPE 1
.\" 27 december 2011
.SH NAME
enpipe \- pipe shoving
.SH SYNOPSIS
.B enpipe
[
.B -in
]
[
.B -o
.I outfile
]
.I command-line
.SH DESCRIPTION
.I Enpipe
runs
.IR command-line ,
substituting arguments consisting solely of
.B -
for a temporary file where standard input is sent to, effectively forcing the named program to work in a pipeline.
If no
.B -
is found, the temporary file's name is added to the end of
.IR command-line .
If either
.B -i
or
.B -n
are passed (they are equivalent), this is not done (allowing
.I enpipe
to start a pipe or keep standard input).
.LP
By default, the program's standard output is copied to standard output.
The
.B -o
option sends the program's standard output nowhere and, after the program runs, copies the named file to standard output instead.
This is done even if the program fails.
.LP
.I Enpipe
returns the exit status of the program run, except if something happens before the program runs.
.SH EXAMPLES
View an online image and a local one in
.IR eog (1):
.IP
.EX
curl http://example.com/file.png | enpipe eog - local.png
.EE
.LP
Process a
.IR tex (1)
document, converting it to a PDF:
.IP
.EX
echo '\eend' | enpipe -i -o paper.dvi tex paper.tex |
	enpipe dvips -f | ps2pdf > paper.pdf
.EE
.LP
(On some systems,
.IR ps2pdf (1)
may need an option or argument such as the dummy filename
.B -
to read standard input.)
.SH FILES
.B /tmp/enpipestdinXXXXXX
.IP
Standard input is shoved to these files.
.SH DIAGNOSTICS
.I Enpipe
prints its own error messages and quits if something happens while trying to run the program.
Programs are run through
.IR sh (1);
its diagnostics will be used as well.
.I Enpipe
prints an error if something happens while copying
.I outfile
but will quit with the error status returned by the program.
The temporary standard input file is never deleted.
.SH BUGS
That this program exists.
(I may be thinking the problem \(em that some modern Unix programs don't like to work in pipelines \(em may be larger than it actually is, but this program is here anwyay.
Another issue I have is that more programs
.I require
.B -
for standard input and output nowadays, but that's a problem
.I enpipe
can't fix.)
.LP
There should be a more general way to insert the input filename.
If there is a program that uses filename to determine file type, a provision for that would also be desirable.
.LP
.B -o
should probably send program standard output to the terminal.
.LP
If attempting to launch the shell to run the program fails,
.I outfile
will still be read.
In fact, if this behavior is reversed, wouldn't that make
.I enpipe
not behave like an actual pipe program?
.SH AUTHOR
Pietro Gagliardi (pietro10@mac.com)
.SH LICENSES
.I Enpipe
is licensed under the MIT License (http://www.opensource.org/licenses/MIT), alternatively titled Expat License.
.LP
This manpage is licensed as so:
.IP
This work is licensed under the Creative Commons Attribution 3.0 Unported License.
To view a copy of this license, visit http://creativecommons.org/licenses/by/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
